world = (
    (#0
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ), (#1
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W            WWWWWW           EE       W",
        "W            WWWWWW           EE       W",
        "W            WWWWWW                    W",
        "W           WWWWWWW                    W",
        "W           WWWWWWWW                   W",
        "W           WWWWWWWWW                  W",
        "W          WWWWWWWWWW                  W",
        "W          WWWWWWWWWW                  W",
        "W         WWWWWWWWWWW                  W",
        "W         WWWWWWWWWWW                  W",
        "W R       WWWWWWWWWWW                  W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ), (#2
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W                                      W",
        "W            WWWWWWWW                  W",
        "W            WWWWWWWW                  W",
        "W            WWWWWWWW                  W",
        "W           WWWWWWWWW                  W",
        "W           WWWWWWWWW                  W",
        "W           WWWWWWWWW                  W",
        "W          WWWWWWWWWW                  W",
        "W          WWWWWWWWWW                  W",
        "W         WWWWWWWWWWW                  W",
        "W         WWWWWWWWWWW               EE W",
        "W R       WWWWWWWWWWW               EE W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ), 
)